### ISSUE TITLE
Lack of model_b

### ISSUE THREAD

**Issue by GreyGuoweiChen** [PKUbioinfo-Zhulab/DeepHoF#1]
Hello @QianGuoPKU and @PKUbioinfo-Zhulab ,

I have noticed your work recently, which is of great significance during this time when viruses are getting more attention. I am also working on virology and want to apply this work to determine hosts of some viruses. 

However, it seems that your [model_b.h5](https://github.com/PKUbioinfo-Zhulab/DeepHoF/blob/master/model_b.h5) was not submitted to GitHub. And, the link to your lab homepage is out of date. Is there any other access to this model? Appreciate it a lot if any information is provided.

Best wish,
Guowei

**Comment by GreyGuoweiChen** [comment]
When I try to download the repositories by `git clone` , the model cannot be downloaded correctly. It is a little bit confused. Because the model is around 65MB, while the downloaded one contains less than 1kb data.

Thanks

**Comment by QianGuoPKU** [comment]
Hi Guowei,

Thank you for reaching out to us. After a second check, I realized the model_b.h5 was indeed missing. The mistake was caused by a disruption in the uploading of the big file. I will fix the problem later. Please send me your email account so that I can share the model file immediately through the email. 

Best,
Qian

**Comment by QianGuoPKU** [comment]
> Hello @QianGuoPKU and @PKUbioinfo-Zhulab ,
> 
> I have noticed your work recently, which is of great significance during this time when viruses are getting more attention. I am also working on virology and want to apply this work to determine hosts of some viruses.
> 
> However, it seems that your [model_b.h5](https://github.com/PKUbioinfo-Zhulab/DeepHoF/blob/master/model_b.h5) was not submitted to GitHub. And, the link to your lab homepage is out of date. Is there any other access to this model? Appreciate it a lot if any information is provided.
> 
> Best wish, Guowei

Hi Guowei,

Thank you for reaching out to us. After a second check, I realized the model_b.h5 was indeed missing. The mistake was caused by a disruption in the uploading of the big file. I will fix the problem later. Please send me your email account so that I can share the model file immediately through the email.

Best,
Qian

**Comment by GreyGuoweiChen** [comment]
> > Hello @QianGuoPKU and @PKUbioinfo-Zhulab ,
> > I have noticed your work recently, which is of great significance during this time when viruses are getting more attention. I am also working on virology and want to apply this work to determine hosts of some viruses.
> > However, it seems that your [model_b.h5](https://github.com/PKUbioinfo-Zhulab/DeepHoF/blob/master/model_b.h5) was not submitted to GitHub. And, the link to your lab homepage is out of date. Is there any other access to this model? Appreciate it a lot if any information is provided.
> > Best wish, Guowei
> 
> Hi Guowei,
> 
> Thank you for reaching out to us. After a second check, I realized the model_b.h5 was indeed missing. The mistake was caused by a disruption in the uploading of the big file. I will fix the problem later. Please send me your email account so that I can share the model file immediately through the email.
> 
> Best, Qian

Hello Qian,

Thanks for your timely reply! My e-mail address is graveschan@outlook.com
Wish you a good day.

Best,
Guowei
